module.exports = {
  plugins: ['import', 'prettier'],
  rules: {
    curly: [0],
    'lines-around-comment': [0],
    'max-len': [0],
    'no-confusing-arrow': [0],
    'no-mixed-operators': [0],
    'no-tabs': [0],
    'no-unexpected-multiline': [0],
    quotes: [0],
    '@typescript-eslint/quotes': [0],
    'babel/quotes': [0],
    'vue/html-self-closing': [0],
    'vue/max-len': [0],
    'array-bracket-newline': [0],
    'array-bracket-spacing': [0],
    'array-element-newline': [0],
    'arrow-parens': [0],
    'arrow-spacing': [0],
    'block-spacing': [0],
    'brace-style': [0],
    'comma-dangle': [0],
    'comma-spacing': [0],
    'comma-style': [0],
    'computed-property-spacing': [0],
    'dot-location': [0],
    'eol-last': [0],
    'func-call-spacing': [0],
    'function-call-argument-newline': [0],
    'function-paren-newline': [0],
    'generator-star': [0],
    'generator-star-spacing': [0],
    'implicit-arrow-linebreak': [0],
    indent: [0],
    'jsx-quotes': [0],
    'key-spacing': [0],
    'keyword-spacing': [0],
    'linebreak-style': [0],
    'multiline-ternary': [0],
    'newline-per-chained-call': [0],
    'new-parens': [0],
    'no-arrow-condition': [0],
    'no-comma-dangle': [0],
    'no-extra-parens': [0],
    'no-extra-semi': [0],
    'no-floating-decimal': [0],
    'no-mixed-spaces-and-tabs': [0],
    'no-multi-spaces': [0],
    'no-multiple-empty-lines': [0],
    'no-reserved-keys': [0],
    'no-space-before-semi': [0],
    'no-trailing-spaces': [0],
    'no-whitespace-before-property': [0],
    'no-wrap-func': [0],
    'nonblock-statement-body-position': [0],
    'object-curly-newline': [0],
    'object-curly-spacing': [0],
    'object-property-newline': [0],
    'one-var-declaration-per-line': [0],
    'operator-linebreak': [0],
    'padded-blocks': [0],
    'quote-props': [0],
    'rest-spread-spacing': [0],
    semi: [0],
    'semi-spacing': [0],
    'semi-style': [0],
    'space-after-function-name': [0],
    'space-after-keywords': [0],
    'space-before-blocks': [0],
    'space-before-function-paren': [0],
    'space-before-function-parentheses': [0],
    'space-before-keywords': [0],
    'space-in-brackets': [0],
    'space-in-parens': [0],
    'space-infix-ops': [0],
    'space-return-throw-case': [0],
    'space-unary-ops': [0],
    'space-unary-word-ops': [0],
    'switch-colon-spacing': [0],
    'template-curly-spacing': [0],
    'template-tag-spacing': [0],
    'unicode-bom': [0],
    'wrap-iife': [0],
    'wrap-regex': [0],
    'yield-star-spacing': [0],
    '@babel/object-curly-spacing': [0],
    '@babel/semi': [0],
    '@typescript-eslint/brace-style': [0],
    '@typescript-eslint/comma-dangle': [0],
    '@typescript-eslint/comma-spacing': [0],
    '@typescript-eslint/func-call-spacing': [0],
    '@typescript-eslint/indent': [0],
    '@typescript-eslint/keyword-spacing': [0],
    '@typescript-eslint/member-delimiter-style': [0],
    '@typescript-eslint/no-extra-parens': [0],
    '@typescript-eslint/no-extra-semi': [0],
    '@typescript-eslint/object-curly-spacing': [0],
    '@typescript-eslint/semi': [0],
    '@typescript-eslint/space-before-blocks': [0],
    '@typescript-eslint/space-before-function-paren': [0],
    '@typescript-eslint/space-infix-ops': [0],
    '@typescript-eslint/type-annotation-spacing': [0],
    'babel/object-curly-spacing': [0],
    'babel/semi': [0],
    'flowtype/boolean-style': [0],
    'flowtype/delimiter-dangle': [0],
    'flowtype/generic-spacing': [0],
    'flowtype/object-type-curly-spacing': [0],
    'flowtype/object-type-delimiter': [0],
    'flowtype/quotes': [0],
    'flowtype/semi': [0],
    'flowtype/space-after-type-colon': [0],
    'flowtype/space-before-generic-bracket': [0],
    'flowtype/space-before-type-colon': [0],
    'flowtype/union-intersection-spacing': [0],
    'react/jsx-child-element-spacing': [0],
    'react/jsx-closing-bracket-location': [0],
    'react/jsx-closing-tag-location': [0],
    'react/jsx-curly-newline': [0],
    'react/jsx-curly-spacing': [0],
    'react/jsx-equals-spacing': [0],
    'react/jsx-first-prop-new-line': [0],
    'react/jsx-indent': [0],
    'react/jsx-indent-props': [0],
    'react/jsx-max-props-per-line': [0],
    'react/jsx-newline': [0],
    'react/jsx-one-expression-per-line': [0],
    'react/jsx-props-no-multi-spaces': [0],
    'react/jsx-tag-spacing': [0],
    'react/jsx-wrap-multilines': [0],
    'standard/array-bracket-even-spacing': [0],
    'standard/computed-property-even-spacing': [0],
    'standard/object-curly-even-spacing': [0],
    'unicorn/empty-brace-spaces': [0],
    'unicorn/no-nested-ternary': [0],
    'unicorn/number-literal-case': [0],
    'vue/array-bracket-newline': [0],
    'vue/array-bracket-spacing': [0],
    'vue/arrow-spacing': [0],
    'vue/block-spacing': [0],
    'vue/block-tag-newline': [0],
    'vue/brace-style': [0],
    'vue/comma-dangle': [0],
    'vue/comma-spacing': [0],
    'vue/comma-style': [0],
    'vue/dot-location': [0],
    'vue/func-call-spacing': [0],
    'vue/html-closing-bracket-newline': [0],
    'vue/html-closing-bracket-spacing': [0],
    'vue/html-end-tags': [0],
    'vue/html-indent': [0],
    'vue/html-quotes': [0],
    'vue/key-spacing': [0],
    'vue/keyword-spacing': [0],
    'vue/max-attributes-per-line': [0],
    'vue/multiline-html-element-content-newline': [0],
    'vue/mustache-interpolation-spacing': [0],
    'vue/no-extra-parens': [0],
    'vue/no-multi-spaces': [0],
    'vue/no-spaces-around-equal-signs-in-attribute': [0],
    'vue/object-curly-newline': [0],
    'vue/object-curly-spacing': [0],
    'vue/object-property-newline': [0],
    'vue/operator-linebreak': [0],
    'vue/quote-props': [0],
    'vue/script-indent': [0],
    'vue/singleline-html-element-content-newline': [0],
    'vue/space-in-parens': [0],
    'vue/space-infix-ops': [0],
    'vue/space-unary-ops': [0],
    'vue/template-curly-spacing': [0],
    'indent-legacy': [0],
    'no-spaced-func': [0],
    'react/jsx-space-before-closing': [0],
    'no-var': ['warn'],
    'object-shorthand': ['warn', 'properties'],
    'accessor-pairs': [
      'error',
      {
        setWithoutGet: true,
        enforceForClassMembers: true,
        getWithoutSet: false,
      },
    ],
    'array-callback-return': [
      'error',
      {
        allowImplicit: false,
        checkForEach: false,
      },
    ],
    camelcase: [
      'error',
      {
        allow: ['^UNSAFE_'],
        properties: 'never',
        ignoreGlobals: true,
        ignoreDestructuring: false,
        ignoreImports: false,
      },
    ],
    'default-case-last': ['error'],
    'dot-notation': [
      'error',
      {
        allowKeywords: true,
        allowPattern: '',
      },
    ],
    eqeqeq: ['error', 'always'],
    'lines-between-class-members': [
      'error',
      'always',
      {
        exceptAfterSingleLine: true,
      },
    ],
    'new-cap': [
      'error',
      {
        newIsCap: true,
        capIsNew: false,
        properties: true,
      },
    ],
    'no-array-constructor': ['error'],
    'no-caller': ['error'],
    'no-case-declarations': ['error'],
    'no-constant-condition': [
      'error',
      {
        checkLoops: false,
      },
    ],
    'no-empty': [
      'error',
      {
        allowEmptyCatch: true,
      },
    ],
    'no-eval': ['error'],
    'no-ex-assign': ['error'],
    'no-extend-native': ['error'],
    'no-extra-bind': ['error'],
    'no-extra-boolean-cast': ['error'],
    'no-fallthrough': ['error'],
    'no-func-assign': ['error'],
    'no-global-assign': ['error'],
    'no-implied-eval': ['error'],
    'no-import-assign': ['error'],
    'no-invalid-regexp': ['error'],
    'no-irregular-whitespace': ['error'],
    'no-iterator': ['error'],
    'no-labels': [
      'error',
      {
        allowLoop: false,
        allowSwitch: false,
      },
    ],
    'no-lone-blocks': ['error'],
    'no-loss-of-precision': ['error'],
    'no-misleading-character-class': ['error'],
    'no-prototype-builtins': ['error'],
    'no-useless-catch': ['error'],
    'no-multi-str': ['error'],
    'no-new': ['error'],
    'no-new-func': ['error'],
    'no-new-object': ['error'],
    'no-new-symbol': ['error'],
    'no-new-wrappers': ['error'],
    'no-obj-calls': ['error'],
    'no-octal': ['error'],
    'no-octal-escape': ['error'],
    'no-proto': ['error'],
    'no-redeclare': [
      'error',
      {
        builtinGlobals: false,
      },
    ],
    'no-regex-spaces': ['error'],
    'no-return-assign': ['error', 'except-parens'],
    'no-self-assign': [
      'error',
      {
        props: true,
      },
    ],
    'no-self-compare': ['error'],
    'no-sequences': ['error'],
    'no-shadow-restricted-names': ['error'],
    'no-sparse-arrays': ['error'],
    'no-template-curly-in-string': ['error'],
    'no-this-before-super': ['error'],
    'no-throw-literal': ['error'],
    'no-undef': ['error'],
    'no-undef-init': ['error'],
    'no-unmodified-loop-condition': ['error'],
    'no-unneeded-ternary': [
      'error',
      {
        defaultAssignment: false,
      },
    ],
    'no-unreachable': ['error'],
    'no-unreachable-loop': ['error'],
    'no-unsafe-finally': ['error'],
    'no-unsafe-negation': ['error'],
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
        enforceForJSX: false,
      },
    ],
    'no-unused-vars': [
      'error',
      {
        args: 'none',
        caughtErrors: 'none',
        ignoreRestSiblings: true,
        vars: 'all',
      },
    ],
    'no-use-before-define': [
      'error',
      {
        functions: false,
        classes: false,
        variables: false,
      },
    ],
    'no-useless-call': ['error'],
    'no-useless-computed-key': ['error'],
    'no-useless-constructor': ['error'],
    'no-useless-escape': ['error'],
    'no-useless-rename': ['error'],
    'no-useless-return': ['error'],
    'no-void': ['error'],
    'no-with': ['error'],
    'one-var': [
      'error',
      {
        initialized: 'never',
      },
    ],
    'prefer-const': [
      'error',
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: false,
      },
    ],
    'prefer-promise-reject-errors': ['error'],
    'prefer-regex-literals': [
      'error',
      {
        disallowRedundantWrapping: true,
      },
    ],
    'spaced-comment': [
      'error',
      'always',
      {
        line: {
          markers: ['*package', '!', '/', ',', '='],
        },
        block: {
          balanced: true,
          markers: ['*package', '!', ',', ':', '::', 'flow-include'],
          exceptions: ['*'],
        },
      },
    ],
    'symbol-description': ['error'],
    'use-isnan': [
      'error',
      {
        enforceForSwitchCase: true,
        enforceForIndexOf: true,
      },
    ],
    'valid-typeof': [
      'error',
      {
        requireStringLiterals: true,
      },
    ],
    yoda: ['error'],
    'import/no-unresolved': ['error'],
    'import/named': ['error'],
    'import/namespace': ['error'],
    'import/default': ['error'],
    'import/export': ['error'],
    'import/no-named-as-default': ['warn'],
    'import/no-named-as-default-member': ['warn'],
    'import/no-duplicates': ['warn'],
    'import/order': [
      'error',
      {
        alphabetize: {
          order: 'asc',
          caseInsensitive: false,
        },
        warnOnUnassignedImports: false,
      },
    ],
    'import/no-default-export': ['error'],
    'prettier/prettier': ['error'],
    'constructor-super': ['error'],
    'for-direction': ['error'],
    'getter-return': ['error'],
    'no-async-promise-executor': ['error'],
    'no-class-assign': ['error'],
    'no-compare-neg-zero': ['error'],
    'no-cond-assign': ['error'],
    'no-const-assign': ['error'],
    'no-control-regex': ['error'],
    'no-debugger': ['error'],
    'no-delete-var': ['error'],
    'no-dupe-args': ['error'],
    'no-dupe-class-members': ['error'],
    'no-dupe-else-if': ['error'],
    'no-dupe-keys': ['error'],
    'no-duplicate-case': ['error'],
    'no-empty-character-class': ['error'],
    'no-empty-pattern': ['error'],
    'no-inner-declarations': ['error'],
    'no-nonoctal-decimal-escape': ['error'],
    'no-setter-return': ['error'],
    'no-unsafe-optional-chaining': ['error'],
    'no-unused-labels': ['error'],
    'no-useless-backreference': ['error'],
    'require-yield': ['error'],
  },
};
